#!/usr/bin/env Rscript
##############################################################################
## scripts/check_ci_check_table.R                                           ##
## Regression check: the CI guide's check table lists every check           ##
##############################################################################
#
# Usage:
#   Rscript scripts/check_ci_check_table.R
#
# Exits 0 when every assertion passes and 1 otherwise, so it can gate a pull
# request.
#
# Why this check exists. The per-check record that preceded the generated table
# listed twenty-six of the fifty-odd checks that existed, because nothing tied it
# to the suite and each check added afterwards went unrecorded. The table in
# docs/Continuous_Integration.md is now generated by scripts/render_check_table.R
# from the checks themselves, and this check asserts three things about it: that
# the guide's table is exactly what the generator builds from the checks as they
# stand, so a check added, renamed or reclassified without regenerating it fails
# here; that every check the runner would discover has a row; and that no row
# names a check that no longer exists.

invisible(Sys.setlocale("LC_CTYPE", "C.UTF-8"))

source("scripts/render_check_table.R")

failures <- character(0)

#' Record a failure
#'
#' @param ... Arguments passed to `sprintf()` to build the message.
#' @return The accumulated failures, invisibly; called for its side effect.
fail <- function(...) {
  assign("failures", c(failures, sprintf(...)), envir = globalenv())
}

#' Print one PASS or FAIL line and record a failure
#'
#' @param ok Whether the assertion held.
#' @param fmt `sprintf()` format string describing the assertion.
#' @param ... Values interpolated into `fmt`.
#' @return The printed line, invisibly; called for its side effect.
report <- function(ok, fmt, ...) {
  msg <- sprintf(fmt, ...)
  cat(sprintf("[%s] %s\n", if (ok) "PASS" else "FAIL", msg))
  if (!ok) fail("%s", msg)
}

guide <- readLines(GUIDE_PATH, encoding = "UTF-8", warn = FALSE)
start <- which(guide == TABLE_START)
end <- which(guide == TABLE_END)
report(length(start) == 1L && length(end) == 1L && end > start,
       "the guide carries one table between its start and end markers")

if (length(start) == 1L && length(end) == 1L && end > start) {
  printed <- guide[(start + 1L):(end - 1L)]
  built <- build_check_table()
  report(identical(printed, built),
         "the guide's table equals the table built from the checks (%d rows printed, %d built)",
         length(printed) - 2L, length(built) - 2L)

  checks <- list.files(CHECK_DIR, pattern = CHECK_PATTERN)
  named <- sub("^\\| `([^`]+)`.*$", "\\1", printed[grepl("^\\| `check_", printed)])
  report(all(checks %in% named), "every check has a row (missing: %s)",
         paste(setdiff(checks, named), collapse = ", "))
  report(all(named %in% checks), "no row names a check that does not exist (stale: %s)",
         paste(setdiff(named, checks), collapse = ", "))
  report(all(slow_checks() %in% checks), "every check the runner classifies slow exists")
  report(!any(grepl("not yet measured", printed)),
         "every check has a measured runtime in scripts/check_runtimes.csv")
}

if (length(failures) > 0L) {
  cat(sprintf("\n%d check(s) FAILED:\n", length(failures)))
  for (f in failures) cat("  - ", f, "\n", sep = "")
  cat("\nRegenerate with `Rscript scripts/render_check_table.R --refresh-baseline`.\n")
  quit(status = 1L)
}
cat("\nThe CI guide lists every check.\n")
quit(status = 0L)
